/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.main;

import java.awt.CardLayout;
import java.awt.Window;

import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

import business.enterprise.Enterprise;
import business.enterprise.PlatformEnterprise;
import business.enterprise.SupplierEnterprise;
import business.network.Network;
import ui.logistics.ManageShipmentsJPanel;
import ui.order.OrderJPanel;
import ui.product.ManageProductJPanel;
import ui.report.ReportViewerJPanel;


/**
 *
 * @author stelladong
 */
public class AdminWorkAreaJPanel extends javax.swing.JPanel {

    private Enterprise enterprise;
    private Network network;

    /**
     * Creates new form AdminWorkAreaJPanel
     */
    public AdminWorkAreaJPanel(Network network, Enterprise enterprise) {
        initComponents();
        this.network = network;
        this.enterprise = enterprise;
        jSplitPane1.setDividerLocation(200);

        SwingUtilities.invokeLater(() -> {
            Window w = SwingUtilities.getWindowAncestor(this);
            if (w != null) {
                w.setSize(900, 700);
                w.setLocationRelativeTo(null);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        btnManageProducts = new javax.swing.JButton();
        btnViewOrders = new javax.swing.JButton();
        btnViewReports = new javax.swing.JButton();
        btnManageUsers = new javax.swing.JButton();
        btnSystemOverview = new javax.swing.JButton();
        btnManageShipments = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        workArea = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        btnManageProducts.setText("Manage Products");
        btnManageProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageProductsActionPerformed(evt);
            }
        });

        btnViewOrders.setText("Manage Orders");
        btnViewOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewOrdersActionPerformed(evt);
            }
        });

        btnViewReports.setText("View Reports");
        btnViewReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewReportsActionPerformed(evt);
            }
        });

        btnManageUsers.setText("Manage Users");
        btnManageUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageUsersActionPerformed(evt);
            }
        });

        btnSystemOverview.setText("System Overview");
        btnSystemOverview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSystemOverviewActionPerformed(evt);
            }
        });

        btnManageShipments.setText("Manage Shipments");
        btnManageShipments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageShipmentsActionPerformed(evt);
            }
        });

        jButton1.setText("Logout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton1.setText("Logout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSystemOverview)
                            .addComponent(btnManageShipments)
                            .addComponent(btnManageUsers)
                            .addComponent(btnManageProducts)
                            .addComponent(btnViewOrders)
                            .addComponent(btnViewReports)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(btnManageUsers)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnManageProducts)
                .addGap(18, 18, 18)
                .addComponent(btnManageShipments)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnViewOrders)
                .addGap(18, 18, 18)
                .addComponent(btnViewReports)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSystemOverview)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(148, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        workArea.setLayout(new java.awt.CardLayout());

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setText("System Admin Dashboard");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        workArea.add(jLabel1, "card2");

        jSplitPane1.setRightComponent(workArea);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageProductsActionPerformed
        SupplierEnterprise supplierEnterprise = null;

        for (Enterprise e : network.getEnterprises()) {
            if (e instanceof SupplierEnterprise) {
                supplierEnterprise = (SupplierEnterprise) e;
                break;
            }
        }

        if (supplierEnterprise == null) {
            JOptionPane.showMessageDialog(this, "Supplier enterprise not found.");
            return;
        }

        ManageProductJPanel panel = new ManageProductJPanel(workArea, supplierEnterprise);
        workArea.add("ManageProductJPanel", panel);

        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.show(workArea, "ManageProductJPanel");
    }//GEN-LAST:event_btnManageProductsActionPerformed

    private void btnViewOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewOrdersActionPerformed
        PlatformEnterprise platformEnterprise = null;

        for (Enterprise e : network.getEnterprises()) {
            if (e instanceof PlatformEnterprise) {
                platformEnterprise = (PlatformEnterprise) e;
                break;
            }
        }

        if (platformEnterprise == null) {
            JOptionPane.showMessageDialog(this, "Platform enterprise not found.");
            return;
        }

        OrderJPanel panel = new OrderJPanel(workArea, platformEnterprise);
        workArea.add("OrderJPanel", panel);

        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.show(workArea, "OrderJPanel");
    }//GEN-LAST:event_btnViewOrdersActionPerformed

    private void btnViewReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewReportsActionPerformed
        PlatformEnterprise platformEnterprise = null;

        for (Enterprise e : network.getEnterprises()) {
            if (e instanceof PlatformEnterprise) {
                platformEnterprise = (PlatformEnterprise) e;
                break;
            }
        }

        if (platformEnterprise == null) {
            JOptionPane.showMessageDialog(this, "Platform enterprise not found.");
            return;
        }

        ReportViewerJPanel panel = new ReportViewerJPanel(workArea, platformEnterprise);
        workArea.add("ReportViewerJPanel", panel);

        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.show(workArea, "ReportViewerJPanel");
    }//GEN-LAST:event_btnViewReportsActionPerformed

        for (Enterprise e : network.getEnterprises()) {
            if (e instanceof PlatformEnterprise) {
                platformEnterprise = (PlatformEnterprise) e;
                break;
            }
        }

        if (platformEnterprise == null) {
            JOptionPane.showMessageDialog(this, "Platform enterprise not found.");
            return;
        }

        ReportViewerJPanel panel = new ReportViewerJPanel(workArea, platformEnterprise);
        workArea.add("ReportViewerJPanel", panel);

        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.show(workArea, "ReportViewerJPanel");
    }//GEN-LAST:event_btnViewReportsActionPerformed

    private void btnManageUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageUsersActionPerformed
        ManageUsersJPanel panel = new ManageUsersJPanel(workArea, network);
        workArea.add("ManageUsersJPanel", panel);

        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_btnManageUsersActionPerformed

    private void btnSystemOverviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSystemOverviewActionPerformed
        PlatformEnterprise platformEnterprise = null;
        for (Enterprise e : network.getEnterprises()) {
            if (e instanceof PlatformEnterprise) {
                platformEnterprise = (PlatformEnterprise) e;
                break;
            }
        }

        SystemOverviewJPanel panel = new SystemOverviewJPanel(workArea, network, platformEnterprise);
        workArea.add("SystemOverviewJPanel", panel);

        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.show(workArea, "SystemOverviewJPanel");
    }//GEN-LAST:event_btnSystemOverviewActionPerformed

    private void btnManageShipmentsActionPerformed(java.awt.event.ActionEvent evt) {
        ManageShipmentsJPanel panel = new ManageShipmentsJPanel(workArea, network);
        workArea.add("ManageShipmentsJPanel", panel);

        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Window window = SwingUtilities.getWindowAncestor(this);
        if (window != null) {
            window.dispose();
        }
        new LoginJFrame(network).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageProducts;
    private javax.swing.JButton btnManageShipments;
    private javax.swing.JButton btnManageUsers;
    private javax.swing.JButton btnSystemOverview;
    private javax.swing.JButton btnViewOrders;
    private javax.swing.JButton btnViewReports;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel workArea;
    // End of variables declaration//GEN-END:variables
}
