/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.main;

import business.enterprise.Enterprise;
import business.user.Person;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import business.user.UserAccount;

/**
 *
 * @author stelladong
 */
public class ManageUsersJPanel extends javax.swing.JPanel {
    private JPanel workArea;
    private Enterprise enterprise;

    /**
     * Creates new form ManageUsersJPanel
     */
  

    /**
     * Creates new form ManageUsersJPanel
     */
    public ManageUsersJPanel(JPanel workArea, Enterprise enterprise) {
        initComponents();
        this.workArea = workArea;
         this.enterprise = enterprise;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsers = new javax.swing.JTable();
        btnAddUser = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();

        jLabel1.setText("Manage Users");

        tblUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "User ID", "User Name", "Role", "Last Access", "Last Updated"
            }
        ));
        jScrollPane1.setViewportView(tblUsers);

        btnAddUser.setText("Add User");
        btnAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddUserActionPerformed(evt);
            }
        });

        jButton1.setText("Delete User");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnNext.setText("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
            .addGroup(layout.createSequentialGroup()
                .addGap(253, 253, 253)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(btnBack)
                .addGap(78, 78, 78)
                .addComponent(jButton1)
                .addGap(80, 80, 80)
                .addComponent(btnAddUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(btnNext)
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddUser)
                    .addComponent(jButton1)
                    .addComponent(btnBack)
                    .addComponent(btnNext))
                .addContainerGap(122, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddUserActionPerformed
                                       
    String username = JOptionPane.showInputDialog(this, "Enter Username:");
    if (username == null || username.trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Username cannot be empty.");
        return;
    }

    String password = JOptionPane.showInputDialog(this, "Enter Password:");
    if (password == null || password.trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Password cannot be empty.");
        return;
    }

    String role = JOptionPane.showInputDialog(this, "Enter Role:");
    if (role == null || role.trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Role cannot be empty.");
        return;
    }

    Person person = new Person(username.trim(), "N/A");

    enterprise.getUserAccountDirectory().addUserAccount(
            username.trim(),
            password.trim(),
            role.trim(),
            person
    );

    populateTable();

    JOptionPane.showMessageDialog(this, "User added successfully.");
        
        
        
    }//GEN-LAST:event_btnAddUserActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
    int selectedRow = tblUsers.getSelectedRow();

    if (selectedRow < 0) {
        JOptionPane.showMessageDialog(this, "Please select a user first.");
        return;
    }

    DefaultTableModel model = (DefaultTableModel) tblUsers.getModel();
    UserAccount userAccount = (UserAccount) model.getValueAt(selectedRow, 0);

    AdminUserAccountJPanel panel = new AdminUserAccountJPanel(
            workArea,
            enterprise,
            userAccount.getUsername(),
            userAccount.getUsername(),
            userAccount.getRole(),
            this
    );

    workArea.add("AdminUserAccountJPanel", panel);
    CardLayout layout = (CardLayout) workArea.getLayout();
    layout.next(workArea);
    }//GEN-LAST:event_btnNextActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 int selectedRow = tblUsers.getSelectedRow();

    if (selectedRow < 0) {
        JOptionPane.showMessageDialog(this, "Please select a user to delete.");
        return;
    }

    int confirm = JOptionPane.showConfirmDialog(
            this,
            "Are you sure?",
            "Confirm Delete",
            JOptionPane.YES_NO_OPTION
    );

    if (confirm != JOptionPane.YES_OPTION) {
        return;
    }

    DefaultTableModel model = (DefaultTableModel) tblUsers.getModel();
    UserAccount userAccount = (UserAccount) model.getValueAt(selectedRow, 0);

    enterprise.getUserAccountDirectory().deleteUserAccount(userAccount);

    populateTable();

    JOptionPane.showMessageDialog(this, "User deleted.");



    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

  if (workArea == null) {
            JOptionPane.showMessageDialog(this, "workArea is null!");
            return;
        }

        workArea.remove(this);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.previous(workArea);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddUser;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblUsers;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
   DefaultTableModel model = (DefaultTableModel) tblUsers.getModel();
    model.setRowCount(0);

    for (UserAccount userAccount : enterprise.getUserAccountDirectory().getUserAccountList()) {
        Object[] row = new Object[5];
        row[0] = userAccount;
        row[1] = userAccount.getUsername();
        row[2] = userAccount.getRole();
        row[3] = "N/A";
        row[4] = "N/A";

        model.addRow(row);
    }
    }
}

