/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.main;

import business.enterprise.Enterprise;
import java.awt.CardLayout;
import ui.order.OrderJPanel;
import ui.report.ReportViewerJPanel;
/**
 *
 * @author stelladong
 */
public class PlatformWorkAreaJPanel extends javax.swing.JPanel {

    private Enterprise enterprise;

    public PlatformWorkAreaJPanel(Enterprise enterprise) {
        initComponents();
        this.enterprise = enterprise;
        jSplitPane1.setDividerLocation(180);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        menuPanel = new javax.swing.JPanel();
        btnViewOrders = new javax.swing.JButton();
        btnViewReports = new javax.swing.JButton();
        btnCustomerService = new javax.swing.JButton();
        btnReturns = new javax.swing.JButton();
        workArea = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setLayout(new java.awt.BorderLayout());

        btnViewOrders.setText("Manage Orders");
        btnViewOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewOrdersActionPerformed(evt);
            }
        });

        btnViewReports.setText("View Reports");
        btnViewReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewReportsActionPerformed(evt);
            }
        });

        btnCustomerService.setText("Customer Service");

        btnReturns.setText("Returns ");

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnViewReports)
                    .addComponent(btnViewOrders)
                    .addComponent(btnCustomerService)
                    .addComponent(btnReturns))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(btnViewOrders)
                .addGap(18, 18, 18)
                .addComponent(btnCustomerService)
                .addGap(18, 18, 18)
                .addComponent(btnReturns)
                .addGap(59, 59, 59)
                .addComponent(btnViewReports)
                .addContainerGap(115, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(menuPanel);

        workArea.setLayout(new java.awt.CardLayout());

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setText("Platform Manager Dashboard");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        workArea.add(jLabel1, "card2");

        jSplitPane1.setRightComponent(workArea);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewOrdersActionPerformed
        OrderJPanel panel = new OrderJPanel(workArea, enterprise);
        workArea.add("OrderPanel", panel);

        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.show(workArea, "OrderPanel");

    }//GEN-LAST:event_btnViewOrdersActionPerformed

    private void btnViewReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewReportsActionPerformed
        ReportViewerJPanel panel = new ReportViewerJPanel(workArea, enterprise);
        workArea.add("ReportViewerJPanel", panel);

        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.show(workArea, "ReportViewerJPanel");
        
        
        
        
        
    }//GEN-LAST:event_btnViewReportsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCustomerService;
    private javax.swing.JButton btnReturns;
    private javax.swing.JButton btnViewOrders;
    private javax.swing.JButton btnViewReports;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JPanel workArea;
    // End of variables declaration//GEN-END:variables
}
