/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.logistics;

import java.awt.CardLayout;
import java.awt.Window;
import java.awt.event.ActionEvent;

import javax.swing.SwingUtilities;

import business.enterprise.LogisticsEnterprise;
import business.network.Network;
import ui.main.LoginJFrame;

/**
 *
 * @author a1
 */
public class LogisticsWorkAreaJPanel extends javax.swing.JPanel {

	 private Network network;
	 private LogisticsEnterprise enterprise;
	    
    /**
     * Creates new form LogisticsWorkAreaJPanel
     */
    public LogisticsWorkAreaJPanel() {
        initComponents();
    }
    
    // 构造器改为：
    public LogisticsWorkAreaJPanel(Network network, LogisticsEnterprise enterprise) {
        initComponents();
        this.network = network;
        this.enterprise = enterprise;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
 
}
