/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.order;
import business.enterprise.PlatformEnterprise;
import business.order.Order;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author stelladong
 */
public class OrderJPanel extends javax.swing.JPanel {
    private javax.swing.JPanel workArea;
    private PlatformEnterprise platformEnterprise;
    private ArrayList<Order> orderList;

    

    public OrderJPanel(JPanel workArea, PlatformEnterprise enterprise) {
        initComponents();
        this.workArea = workArea;
        this.platformEnterprise = enterprise;
        orderList = platformEnterprise.getOrderDirectory().getOrderList();
        populateTable();
    }

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

        for (Order order : orderList) {
            Object[] row = new Object[4];
            row[0] = order;
            row[1] = order.getStatus();
            row[2] = order.getTotalPrice();
            row[3] = order.getRiskFlag();
            model.addRow(row);
    }
    }
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnViewDetail = new javax.swing.JButton();
        btnMarkShipped = new javax.swing.JButton();
        btnMarkDelivered = new javax.swing.JButton();
        btnCreateOrder = new javax.swing.JButton();
        btnCancelOrder = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Order ID", "Status", "Total Price", "Risk Flag"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnViewDetail.setText("View Detail");
        btnViewDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDetailActionPerformed(evt);
            }
        });

        btnMarkShipped.setText("Mark Shipped");
        btnMarkShipped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarkShippedActionPerformed(evt);
            }
        });

        btnMarkDelivered.setText("Mark Delivered");
        btnMarkDelivered.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarkDeliveredActionPerformed(evt);
            }
        });

        btnCreateOrder.setText("Create Order");
        btnCreateOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateOrderActionPerformed(evt);
            }
        });

        btnCancelOrder.setText("Cancel Order");
        btnCancelOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelOrderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(139, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(btnViewDetail)
                .addGap(18, 18, 18)
                .addComponent(btnMarkShipped)
                .addGap(18, 18, 18)
                .addComponent(btnMarkDelivered)
                .addGap(18, 18, 18)
                .addComponent(btnCreateOrder)
                .addGap(18, 18, 18)
                .addComponent(btnCancelOrder)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewDetail)
                    .addComponent(btnMarkShipped)
                    .addComponent(btnMarkDelivered)
                    .addComponent(btnCreateOrder)
                    .addComponent(btnCancelOrder))
                .addContainerGap(68, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDetailActionPerformed
   int selectedRow = jTable1.getSelectedRow();

        if (selectedRow < 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select an order.");
            return;
        }

        Order order = (Order) jTable1.getValueAt(selectedRow, 0);

        OrderDetailJPanel panel = new OrderDetailJPanel(workArea, order);
        workArea.add("OrderDetailJPanel", panel);

        java.awt.CardLayout layout = (java.awt.CardLayout) workArea.getLayout();
        layout.show(workArea, "OrderDetailJPanel");
        
        
        
    }//GEN-LAST:event_btnViewDetailActionPerformed

    private void btnMarkShippedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarkShippedActionPerformed
        Order order = getSelectedOrder();
        if (order == null) {
            return;
        }
        order.setShipmentStatus("Shipped");
        order.setStatus("Shipped");
        populateTable();
    }//GEN-LAST:event_btnMarkShippedActionPerformed

    private void btnMarkDeliveredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarkDeliveredActionPerformed
        Order order = getSelectedOrder();
        if (order == null) {
            return;
        }
        if (!"Shipped".equalsIgnoreCase(order.getShipmentStatus())) {
            JOptionPane.showMessageDialog(this, "Order must be shipped before delivered.");
            return;
        }
        order.setShipmentStatus("Delivered");
        order.setStatus("Completed");
        populateTable();
    }//GEN-LAST:event_btnMarkDeliveredActionPerformed

    private void btnCreateOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateOrderActionPerformed
        String customerName = JOptionPane.showInputDialog(this, "Customer name:");
        String err = business.ValidationHelper.validateName(customerName);
        if (err != null) { JOptionPane.showMessageDialog(this, err); return; }

        String email = JOptionPane.showInputDialog(this, "Customer email:");
        err = business.ValidationHelper.validateEmail(email);
        if (err != null) { JOptionPane.showMessageDialog(this, err); return; }

        String country = JOptionPane.showInputDialog(this, "Destination country:");
        if (country == null || country.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Country is required.");
            return;
        }

        platformEnterprise.getOrderDirectory().addOrder(
                customerName.trim(),
                email.trim(),
                country.trim()
        );
        populateTable();
    }//GEN-LAST:event_btnCreateOrderActionPerformed

    private void btnCancelOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelOrderActionPerformed
        Order order = getSelectedOrder();
        if (order == null) {
            return;
        }
        if ("Delivered".equalsIgnoreCase(order.getShipmentStatus())) {
            JOptionPane.showMessageDialog(this, "Delivered order cannot be cancelled.");
            return;
        }
        order.setStatus("Cancelled");
        order.setShipmentStatus("Cancelled");
        populateTable();
    }//GEN-LAST:event_btnCancelOrderActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelOrder;
    private javax.swing.JButton btnCreateOrder;
    private javax.swing.JButton btnMarkDelivered;
    private javax.swing.JButton btnMarkShipped;
    private javax.swing.JButton btnViewDetail;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private Order getSelectedOrder() {
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select an order first.");
            return null;
        }
        return (Order) jTable1.getValueAt(selectedRow, 0);
    }
}