/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.order;
import business.enterprise.Enterprise;
import business.order.Order;
import business.order.OrderItem;
import business.product.Product;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author stelladong
 */
public class OrderJPanel extends javax.swing.JPanel {
    private javax.swing.JPanel workArea;
    private Enterprise enterprise;
    private ArrayList<Order> orderList;

    

    public OrderJPanel(JPanel workArea, Enterprise enterprise) {
        initComponents();
        this.workArea = workArea;
        this.enterprise = enterprise;
        
        orderList = new ArrayList<>();
        loadDemoOrders();
        populateTable();
    }

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

        for (Order order : orderList) {
            Object[] row = new Object[3];
            row[0] = order;
            row[1] = order.getStatus();
            row[2] = order.getTotalPrice();
            model.addRow(row);
    }
    }
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnViewDetail = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Order ID", "Status", "Total Price"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnViewDetail.setText("View Detail");
        btnViewDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDetailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(139, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(btnViewDetail)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addComponent(btnViewDetail)
                .addContainerGap(68, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDetailActionPerformed
 int selectedRow = jTable1.getSelectedRow();

    if (selectedRow < 0) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please select an order.");
        return;
    }

    Order order = (Order) jTable1.getValueAt(selectedRow, 0);

    OrderDetailJPanel panel = new OrderDetailJPanel(workArea, order);
    workArea.add("OrderDetailJPanel", panel);

    java.awt.CardLayout layout = (java.awt.CardLayout) workArea.getLayout();
    layout.show(workArea, "OrderDetailJPanel");
        
        
        
    }//GEN-LAST:event_btnViewDetailActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnViewDetail;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private void loadDemoOrders() {
        Product p1 = new Product("iPhone", 1000);
        Product p2 = new Product("Laptop", 2000);
        Product p3 = new Product("Headphones", 300);

        Order order1 = new Order();
        order1.setOrderId("ORD001");
        order1.setStatus("Created");
        order1.addItem(new OrderItem(p1, 2, 900));
        order1.addItem(new OrderItem(p3, 2, 250));

        Order order2 = new Order();
        order2.setOrderId("ORD002");
        order2.setStatus("Shipped");
        order2.addItem(new OrderItem(p2, 1, 1800));

        orderList.add(order1);
        orderList.add(order2);    }
}
