/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.report;

import business.enterprise.Enterprise;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author stelladong
 */
public class ReportViewerJPanel extends javax.swing.JPanel {
 private JPanel workArea;
 private Enterprise enterprise;

    /**
     * Creates new form ReportViewerPanel
     */
     public ReportViewerJPanel(JPanel workArea, Enterprise enterprise) {
        initComponents();
        this.workArea = workArea;
        this.enterprise = enterprise;

        populateOrderSummaryTable();
        populateShipmentSummaryTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelOrderSummary = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrderSummary = new javax.swing.JTable();
        panelShipmentSummary = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblShipmentSummary = new javax.swing.JTable();

        jLabel1.setText("Report Viewer Panel");

        tblOrderSummary.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Order ID", "Status", "Total Price"
            }
        ));
        jScrollPane1.setViewportView(tblOrderSummary);

        javax.swing.GroupLayout panelOrderSummaryLayout = new javax.swing.GroupLayout(panelOrderSummary);
        panelOrderSummary.setLayout(panelOrderSummaryLayout);
        panelOrderSummaryLayout.setHorizontalGroup(
            panelOrderSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOrderSummaryLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        panelOrderSummaryLayout.setVerticalGroup(
            panelOrderSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOrderSummaryLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Order Summary", panelOrderSummary);

        tblShipmentSummary.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Shipment ID ", " Order ID", "Status", "ETA"
            }
        ));
        jScrollPane2.setViewportView(tblShipmentSummary);

        javax.swing.GroupLayout panelShipmentSummaryLayout = new javax.swing.GroupLayout(panelShipmentSummary);
        panelShipmentSummary.setLayout(panelShipmentSummaryLayout);
        panelShipmentSummaryLayout.setHorizontalGroup(
            panelShipmentSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelShipmentSummaryLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );
        panelShipmentSummaryLayout.setVerticalGroup(
            panelShipmentSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelShipmentSummaryLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Shipment Summary", panelShipmentSummary);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel panelOrderSummary;
    private javax.swing.JPanel panelShipmentSummary;
    private javax.swing.JTable tblOrderSummary;
    private javax.swing.JTable tblShipmentSummary;
    // End of variables declaration//GEN-END:variables

    private void populateOrderSummaryTable() {
    DefaultTableModel model = (DefaultTableModel) tblOrderSummary.getModel();
    model.setRowCount(0);

    Object[] row1 = {"O001", "Processing", 120.00};
    Object[] row2 = {"O002", "Completed", 88.50};

    model.addRow(row1);
    model.addRow(row2);    
        
        
        
        
        
        
    }

    private void populateShipmentSummaryTable() {
    DefaultTableModel model = (DefaultTableModel) tblShipmentSummary.getModel();
    model.setRowCount(0);

    Object[] row1 = {"S001", "O001", "In Transit", "2026-04-10"};
    Object[] row2 = {"S002", "O002", "Delivered", "2026-04-08"};

    model.addRow(row1);
    model.addRow(row2);
        
        
        
    }
}
