/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.report;

import business.enterprise.Enterprise;
import business.order.Order;
import business.order.OrderItem;
import business.product.Product;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author stelladong
 */
public class ReportViewerJPanel extends javax.swing.JPanel {
 private JPanel workArea;
 private Enterprise enterprise;

    /**
     * Creates new form ReportViewerPanel
     */
     public ReportViewerJPanel(JPanel workArea, Enterprise enterprise) {
        initComponents();
        this.workArea = workArea;
        this.enterprise = enterprise;

        populateOrderSummaryTable();
        populateShipmentSummaryTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelOrderSummary = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrderSummary = new javax.swing.JTable();
        panelShipmentSummary = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblShipmentSummary = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();

        jLabel1.setText("Report Viewer Panel");

        tblOrderSummary.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Order ID", "Status", "Total Price", "Risk Alert"
            }
        ));
        jScrollPane1.setViewportView(tblOrderSummary);

        javax.swing.GroupLayout panelOrderSummaryLayout = new javax.swing.GroupLayout(panelOrderSummary);
        panelOrderSummary.setLayout(panelOrderSummaryLayout);
        panelOrderSummaryLayout.setHorizontalGroup(
            panelOrderSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOrderSummaryLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        panelOrderSummaryLayout.setVerticalGroup(
            panelOrderSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOrderSummaryLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Order Summary", panelOrderSummary);

        tblShipmentSummary.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Shipment ID ", " Order ID", "Status", "ETA"
            }
        ));
        jScrollPane2.setViewportView(tblShipmentSummary);

        javax.swing.GroupLayout panelShipmentSummaryLayout = new javax.swing.GroupLayout(panelShipmentSummary);
        panelShipmentSummary.setLayout(panelShipmentSummaryLayout);
        panelShipmentSummaryLayout.setHorizontalGroup(
            panelShipmentSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelShipmentSummaryLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );
        panelShipmentSummaryLayout.setVerticalGroup(
            panelShipmentSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelShipmentSummaryLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Shipment Summary", panelShipmentSummary);

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(84, 84, 84))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnBack))
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

    workArea.remove(this);
    java.awt.CardLayout layout = (java.awt.CardLayout) workArea.getLayout();
    layout.previous(workArea);

    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel panelOrderSummary;
    private javax.swing.JPanel panelShipmentSummary;
    private javax.swing.JTable tblOrderSummary;
    private javax.swing.JTable tblShipmentSummary;
    // End of variables declaration//GEN-END:variables

    private void populateOrderSummaryTable() {
    DefaultTableModel model = (DefaultTableModel) tblOrderSummary.getModel();
    model.setRowCount(0);

     for (Order order : getDemoOrders()) {
        Object[] row = new Object[4];
        row[0] = order.getOrderId();
        row[1] = order.getStatus();
        row[2] = order.getTotalPrice();
        row[3] = getRiskAlert(order);
        model.addRow(row);   
     }  
    }
    private String getRiskAlert(Order order) {
    if (order.getTotalPrice() > 1000) {
        return "High Value Alert";
    }
    return "";
}
    private ArrayList<Order> getDemoOrders() {
    ArrayList<Order> list = new ArrayList<>();

    Product p1 = new Product("iPhone", 1000);
    Product p2 = new Product("Laptop", 2000);
    Product p3 = new Product("Headphones", 300);

    Order o1 = new Order();
    o1.setOrderId("ORD001");
    o1.setStatus("Processing");
    o1.addItem(new OrderItem(p1, 1, 1000));
    o1.addItem(new OrderItem(p3, 2, 250));

    Order o2 = new Order();
    o2.setOrderId("ORD002");
    o2.setStatus("Completed");
    o2.addItem(new OrderItem(p2, 1, 1800));

    list.add(o1);
    list.add(o2);

    return list;
}    
        
          
    

    private void populateShipmentSummaryTable() {
    DefaultTableModel model = (DefaultTableModel) tblShipmentSummary.getModel();
    model.setRowCount(0);

    Object[] row1 = {"S001", "O001", "In Transit", "2026-04-10"};
    Object[] row2 = {"S002", "O002", "Delivered", "2026-04-08"};

    model.addRow(row1);
    model.addRow(row2);
        
        
        
    }
}
